pixel_to_km: 2.3109 # DO NOT CHANGE!!!
num_households: 15
num_generations: 500

households:
  num_workers: 5
  grain: 3000
  generation_countdown: 15
  knowledge_ratio: 1.15545   # 0.5 km  per individual (~population density)
  min_competency: 0.2
  min_ambition: 0.2
