pixel_to_km: 2.3109 # DO NOT CHANGE!!!
knowledge_ratio: 1.15545   # 0.5 km  per individual (~population density) -specified in pixels
claim_ratio: 4 # specified in pixels (4 workers per pixel)
worker_capability: 260
worker_appetite: 100
maximum_potential_yield: 40000
growth_rate: 0.02

# Farming inefficiencies remain constant as size of community increases
